# permissions for end users to view verticalpodautoscalers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: verticalpodautoscaler-viewer-role
rules:
- apiGroups:
  - autoscaler.kubebuilder.rym
  resources:
  - verticalpodautoscalers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - autoscaler.kubebuilder.rym
  resources:
  - verticalpodautoscalers/status
  verbs:
  - get
